name: Detect, Test and Publish IB Gateway/TWS Releases

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string

jobs:
  check-new-version:
    name: Check for new IBKR stable/latest versions
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.version.outputs.build_version }}
      tag: docker-${{ steps.version.outputs.build_version }}-${{ inputs.channel }}
      has_update: ${{ steps.check-update.outputs.has_update }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Latest IB Gateway Version
        id: version
        run: |
          res=$(curl -s https://download2.interactivebrokers.com/installers/ibgateway/${{ inputs.channel }}-standalone/version.json)
          build_version=$(grep -oP '(?<=buildVersion":")[^"]+' <<< "$res")
          echo "build_version=$build_version" >> $GITHUB_OUTPUT

      - name: Check Latest Version against Releases
        id: check-update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release list | grep -qF '${{ steps.version.outputs.build_version }}-${{ inputs.channel }}'; then
            echo "has_update=false" >> $GITHUB_OUTPUT
          else
            echo "has_update=true" >> $GITHUB_OUTPUT
          fi

  test-and-commit:
    name: Test version and commit
    runs-on: ubuntu-latest
    needs: check-new-version
    if: needs.check-new-version.outputs.has_update == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Download IB Gateway
        run: |
          download_url='https://download2.interactivebrokers.com/installers/ibgateway/${{ inputs.channel }}-standalone/ibgateway-${{ inputs.channel }}-standalone-linux-x64.sh'
          dest='ibgateway-${{ needs.check-new-version.outputs.build_version }}-standalone-linux-x64.sh'
          curl -sSL "$download_url" --output "$dest"
          sha256sum "$dest" > "${dest}.sha256"

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create '${{ needs.check-new-version.outputs.build_version }}-${{ inputs.channel }}' \
            -t 'ibgateway ${{ needs.check-new-version.outputs.build_version }}-${{ inputs.channel }}' \
            ibgateway-*
          rm ibgateway-*

      - name: Update ${{ inputs.channel }}/ and commit
        run: ./build.sh ${{ inputs.channel }} ${{ needs.check-new-version.outputs.build_version }}   

      - name: Commit with appropriate docker tag
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push_options: '--force'
          commit_message: Update ${{ inputs.channel }} to ${{ needs.check-new-version.outputs.build_version }}

          # By itself, will not trigger docker.yml action due to Github restrictions
          tagging_message: ${{ needs.check-new-version.outputs.tag }}

  build-after-commit:
    name: Trigger Docker Build After Commit
    needs:
      - test-and-commit
      - check-new-version
    # When a new IB release is detected we want to wait for test-and-commit
    # to finish (it creates/releases files and updates the repo) before
    # running the Docker build.
    if: needs.check-new-version.outputs.has_update == 'true'
    uses: ./.github/workflows/docker.yml
    with:
      tag: ${{ needs.check-new-version.outputs.tag }}

  build-direct:
    name: Trigger Docker Build Direct (no commit)
    needs:
      - check-new-version
    # For manual pushes by a user (not the github-actions bot) we want to
    # allow building directly even if test-and-commit was skipped. This
    # branch runs only when there is NO new upstream IB release.
    if: ((github.event_name == 'push' && github.actor != 'github-actions[bot]') || github.event_name == 'workflow_dispatch') && needs.check-new-version.outputs.has_update != 'true'
    uses: ./.github/workflows/docker.yml
    with:
      tag: ${{ needs.check-new-version.outputs.tag }}
